# Generated by Django 5.1.4 on 2024-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, verbose_name="제목")),
                ("company", models.CharField(max_length=50, verbose_name="참조사이트")),
                ("date", models.CharField(max_length=50, verbose_name="날짜")),
                ("href", models.TextField(blank=True, verbose_name="주소")),
            ],
        ),
    ]
